#!/bin/bash
# License: CC0
#
set -e
export LANG=C

function ipv6expand(){
	ip="$1"
	expr "$ip" : '[[:xdigit:]:]\{2,\}$' >/dev/null
	echo $ip |grep -sqEv '[[:xdigit:]]{5}|:::|::.*::' 
	cn=$(echo $ip |grep -o : |wc -l)
	test $cn -ge 2 -a $cn -le 7
	ip=$(echo $ip |sed '
	    s/^:/0000:/
	    s/:$/:0000/
	    s/.*/:&:/
	    :add0
	    s/:\([^:]\{1,3\}\):/:0\1:/g
	    t add0
	    s/:\(.*\):/\1/' )
	if echo $ip |grep -sq :: ; then
	    ip=$(echo $ip |sed s/::/:$(echo -n :::::: |tail -c $((8-cn)) |sed 's/:/0000:/g')/ )
	else
	        test $cn -eq 7
	fi
	echo $ip
	# https://qiita.com/obsolete-standard/items/e410530cecb0a21d3ecc
}

# main
#logger "DEBUG: config-ipv6-netmap start"

/sbin/ip6tables -t raw -S | grep NOTRACK && true
if [ $? -eq 0 ]; then
  /sbin/ip6tables -t raw -D OUTPUT -j NOTRACK
  /sbin/ip6tables -t raw -D PREROUTING -j NOTRACK
fi

/sbin/sysctl -w net.ipv6.conf.all.proxy_ndp=1

PREFIX1=$(/bin/ip -6 r |/bin/sed -n "s/^\([^ ]*\) .*eth0.*256.*/\1/p"|grep -v "^fe80"|/usr/bin/tail -1)
PREFIX2=$(/bin/ip -6 r |/bin/sed -n "s/^\([^ ]*\) .*switch0.*256.*/\1/p"|grep -v "^fe80"|/usr/bin/tail -1)

/sbin/ip6tables -t nat -A POSTROUTING -o eth0 -j NETMAP --to $PREFIX1 -s   $PREFIX2
/sbin/ip6tables -t nat -A PREROUTING  -i eth0 -j NETMAP -d   $PREFIX1 --to $PREFIX2

CTRACK=$(/usr/sbin/conntrack -f ipv6 -L)
( echo "$CTRACK"|awk '!/tcp/{gsub("src=","",$4);print $4}';\
  echo "$CTRACK"|awk  '/tcp/{gsub("src=","",$5);print $5}')|sort -u |\
while read line; do   
  /bin/ip -6 neigh add proxy $(echo "$(ipv6expand $PREFIX1):$(ipv6expand $line)"|awk -F: '{printf "%s:%s:%s:%s:%s:%s:%s:%s\n",$1,$2,$3,$4,$13,$14,$15,$16}') dev eth0 
done

#/bin/ip -6 neigh show proxy|logger
#logger "DEBUG: config-ipv6-netmap done"

