#!/bin/bash
# License: CC0
#
set -e
export LANG=C

# main
/sbin/ip6tables -t raw -S | grep NOTRACK && true
if [ $? -eq 0 ]; then
  /sbin/ip6tables -t raw -D OUTPUT -j NOTRACK
  /sbin/ip6tables -t raw -D PREROUTING -j NOTRACK
fi

/sbin/sysctl -w net.ipv6.conf.all.proxy_ndp=1

PREFIX1=$(/bin/ip -6 r |/bin/sed -n "s/^\([^ ]*\) .*eth0.*256.*/\1/p"|grep -v "^fe80"|/usr/bin/tail -1)
PREFIX2=$(/bin/ip -6 r |/bin/sed -n "s/^\([^ ]*\) .*switch0.*256.*/\1/p"|grep -v "^fe80"|/usr/bin/tail -1)

/sbin/ip6tables -t nat -A POSTROUTING -o eth0 -j NETMAP --to $PREFIX1 -s   $PREFIX2
/sbin/ip6tables -t nat -A PREROUTING  -i eth0 -j NETMAP -d   $PREFIX1 --to $PREFIX2

/usr/sbin/conntrack -f ipv6 -L |
awk '{
    if($1~/tcp/){
        gsub("dst=","",$10); print $10 }
    else{
        gsub("dst=","",$9); print $9
    }}' |
sort -u |
while read line; do
    /bin/ip -6 neigh add proxy $line dev eth0 
done

